steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci']
    
  # Build the frontend
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    
  # Build the backend
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build:server']
    
  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']

# Environment variables for build process
substitutions:
  _NODE_ENV: 'production'

options:
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'
  
timeout: '1200s'